- name: Install apache httpd for RHEL
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- name: Install apache httpd for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'