all:
  hosts:
    dbnode1:
      ansible_host: 192.168.11.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/dbnode1/virtualbox/private_key
    dbnode2:
      ansible_host: 192.168.11.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/dbnode2/virtualbox/private_key
    dbnode3:
      ansible_host: 192.168.11.4
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/dbnode3/virtualbox/private_key
    apnode1:
      ansible_host: 192.168.11.5
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/apnode1/virtualbox/private_key
    apnode2:
      ansible_host: 192.168.11.6
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/apnode2/virtualbox/private_key
    prxnode1:
      ansible_host: 192.168.11.7
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/prxnode1/virtualbox/private_key
    prxnode2:
      ansible_host: 192.168.11.8
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/prxnode2/virtualbox/private_key
    balancer1:
      ansible_host: 10.0.10.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/balancer1/virtualbox/private_key
    balancer2:
      ansible_host: 10.0.10.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/balancer2/virtualbox/private_key
    monitor:
      ansible_host: 172.16.1.2
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/monitoring/virtualbox/private_key
    firewall:
      ansible_host: 172.16.1.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/fw/virtualbox/private_key
    backup:
      ansible_host: 172.16.1.3
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/backup/virtualbox/private_key
backends:
  hosts:
    apnode1: 
    apnode2:
frontends:
  hosts:
    balancer1:
      keepalived_group: frontends
      keepalived_router_id: 10
      keepalived_role: MASTER
      keepalived_vip: 10.0.10.200
      keepalived_track_process: sshd
      keepalived_priority: 200
    balancer2:
      keepalived_group: frontends
      keepalived_router_id: 10
      keepalived_role: BACKUP
      keepalived_vip: 10.0.10.200
      keepalived_track_process: sshd
      keepalived_priority: 190
dbservers:
  hosts:
    dbnode1:
      server_id: 1
      replication_role: master
      backup_prefix: wpdb
    dbnode2:
      server_id: 2
      backup_prefix: wpdb
    dbnode3:
      server_id: 3
      backup_prefix: wpdb
monitoring:
  hosts:
    monitor:
logging:
  hosts:
    monitor:
monitored:
  hosts:
    dbnode1:
    dbnode2:
    dbnode3:
    apnode1:
    apnode2:
    monitor:
    backup:
    firewall:
    balancer1:
    balancer2:
firewalls:
  hosts:
    firewall:
backup_servers:
  hosts:
    backup:
backup_clients:
  hosts:
    dbnode2:
      backup_folder: "/var/backup/{{ wpdb_dbname }}/"
      backup_prefix: "wpdb"
      replication_role: master
haproxys:
  hosts:
    prxnode1:
        keepalived_group: haproxys
        keepalived_router_id: 11
        keepalived_role: MASTER
        keepalived_vip: 192.168.11.56
        keepalived_track_process: haproxy
        keepalived_priority: 200
        haproxy_listen_ip: 0.0.0.0
    prxnode2:
        keepalived_group: haproxys
        keepalived_router_id: 11
        keepalived_role: BACKUP
        keepalived_vip: 192.168.11.56
        keepalived_track_process: haproxy
        keepalived_priority: 190
        haproxy_listen_ip: 0.0.0.0