- name: Ensure that the alertmanager user exists
  user:
    name: "alertmanager"
    shell: /bin/false
- set_fact:
    telepush_token: "{{ lookup('file', telegram_bot_token_file) }}"
- name: Copy binaries
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0755
  with_items:
    - "files/alertmanager"
    - "files/amtool"
- name: Copy systemd service file
  template:
    src: "alertmanager.service.j2"
    dest: "/etc/systemd/system/alertmanager.service"
- name: Ensure alertmanager folder exists in etc
  file:
    state: directory
    path: /etc/alertmanager
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0755
- name: Copy alertmanager config from template
  template:
    src: "alertmanager.yml.j2"
    dest: "/etc/alertmanager/alertmanager.yml"
- name: create /var/lib/prometheus/alertmanager
  file:
    state: directory
    path: /var/lib/prometheus/alertmanager
    recurse: true
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0755
- name: Systemd reload to pickup new service
  systemd:
    daemon-reload: true
    enabled: true
    state: restarted
    name: "alertmanager.service"
  notify: restart_alertmanager_server
- name: Open port 9093 in firewalld
  ansible.posix.firewalld:
    port: 9093/tcp
    permanent: yes
    immediate: yes
    state: enabled