- name: Install php for RHEL
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'
- name: Install php for Debian
  include_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'