---
- name: Download wordpress from official site
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://wordpress.org/wordpress-6.1.1.tar.gz
    dest: "files/wordpress-6.1.1.tar.gz"
- name: Copy wordpress to node
  ansible.builtin.copy:
    src: "files/wordpress-6.1.1.tar.gz"
    dest: "/tmp/wordpress-6.1.1.tar.gz"
- name: Untar wordpress
  ansible.builtin.unarchive:
    src: "/tmp/wordpress-6.1.1.tar.gz"
    dest: "/var/www/html"
    extra_opts: [--strip-components=1]
    remote_src: yes
- set_fact:
    master_ip: "{{ hostvars[item]['ansible_host'] }}"
    master_server: "{{ item }}"
  with_items: "{{ groups.dbservers }}"
  when:
    - hostvars[item].replication_role == 'master'
    - master_ip is not defined
    #  - set_fact:
    #     loadbalancer_ip: "{{ hostvars[item]['ansible_host'] }}"
    #   with_items: "{{ groups.frontends | first }}"
    #   when:
    #     - loadbalancer_ip is not defined
# - set_fact:
#     control_node_ip: "{{ hostvars['127.0.0.1']['ansible_default_ipv4']['address'] }}"
#   run_once: true
#   delegate_to: localhost
#   delegate_facts: true

- name: Copy wp-config
  ansible.builtin.template:
    src: "wp-config.php.j2"
    dest: "/var/www/html/wp-config.php"
