---
- name: Create backup dir
  ansible.builtin.file:
    path: "/var/backup/{{ wpdb_dbname }}/"
    state: directory
  when:
    replication_role == "slave"
- name: Copy backup script
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /opt/backup_db_each_table.sh
    mode: '0700'
    owner: 'root'
    group: 'root'
  when:
    replication_role == "slave"
- name: Setup cron job for backup
  ansible.builtin.cron:
    name: Mysql autobackup on per-table basis
    weekday: "*"
    hour: "12"
    user: root
    cron_file: mysql-per-table-backup
    job: "/opt/backup_db_each_table.sh"
  when:
    replication_role == "slave"
- name: Execute backup once
  ansible.builtin.command: "/opt/backup_db_each_table.sh"
  when:
    replication_role == "slave"