---
- name: Open ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 3306/tcp
    - 4567/tcp
    - 4568/tcp
    - 4444/tcp
    - 4567/udp
- name: Add nodes to public zone
  ansible.posix.firewalld:
    source: "{{ hostvars[item]['ansible_host'] }}"
    state: enabled
    zone: public
    permanent: true
    immediate: true
  with_items: 
    - "{{ groups['dbservers'] }}"
- name: Add tcp ports to mysqld_port_t
  community.general.seport:
    ports: 4567,4568,4444
    proto: tcp
    setype: mysqld_port_t
    state: present
- name: Add udp ports to mysqld_port_t
  community.general.seport:
    ports: 4567
    proto: udp
    setype: mysqld_port_t
    state: present
- name: Compile and install selinux module
  include_tasks: selinux-module-compile.yml