---
- name: Remove SELinux policy package
  ansible.builtin.command: semodule -r galera
  failed_when: false
- name: Copy SELinux type enforcement file
  ansible.builtin.copy:
    src: galera.te
    dest: /tmp/
- name: Compile SELinux module
  ansible.builtin.command: checkmodule -M -m -o /tmp/galera.mod /tmp/galera.te
- name: Build SELinux policy package
  ansible.builtin.command: semodule_package -o /tmp/galera.pp -m /tmp/galera.mod
- name: Load SELinux policy package
  ansible.builtin.command: semodule -i /tmp/galera.pp
- name: Remove temp files
  ansible.builtin.file:
    path: /tmp/galera.*
    state: absent
